package org.xhtmlrenderer.util;

public enum LangId
{
	VALUE_COUNT_MISMATCH,
	MIN_MAX_VALUE_COUNT_MISMATCH,
	MUST_BE_IDENTIFIER,
	MUST_BE_URI_OR_IDENTIFIER,
	MUST_BE_COLOR_OR_IDENTIFIER,
	MUST_BE_INT_OR_IDENTIFIER, 
	MUST_BE_INT,
	MUST_BE_LENGTH_OR_IDENTIFIER,
	MUST_BE_NUMBER_OR_IDENTIFIER,
	MUST_BE_LENGTH_PERCENT_OR_IDENTIFIER,
	MUST_BE_LENGTH_OR_PERCENT,
	MUST_BE_LENGTH,
	MUST_BE_NUMBER,
	MUST_BE_STRING,
	MUST_BE_STRING_OR_IDENTIFIER,
	MUST_BE_LENGTH_NUMBER_PERCENT_OR_IDENTIFIER,
	UNSUPPORTED_IDENTIFIER,
	UNRECOGNIZED_IDENTIFIER,
	INVALID_INHERIT;
}
